server:
  port: 8006
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    instance-id:  ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 2 
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000
